#!/usr/bin/env bash
#Displays "Best School" 10times and "Hi" on the 9th iteration

index=1

while [ $index -le 10 ]
do
	echo "Best School"
	if [ $index -eq 9 ]
	then	
		echo "Hi"
	fi		
	((index++))
done
